### ISSUE TITLE
Nested params support ?

### ISSUE THREAD

**Issue by ernestas-poskus** [shssoichiro/iron-valid#34]
Hey @shssoichiro, thank you for crate.

Have one question about this crate I am interested whether it is possible to validate nested params like in https://github.com/iron/params example.

```rust
match map.find(&["user", "name"]) {
```

If so what is the syntax to do it ?

**Comment by shssoichiro** [comment]
Currently this isn't possible, but it's a feature I've been meaning to add. I've been debating whether the syntax should be `&["user", "name"]` to match `params` or `"user.name"` to keep backwards compatibility. Do you have any input on which you'd prefer?

**Comment by ernestas-poskus** [comment]
> syntax should be &["user", "name"] to match params or "user.name"

If in the context of HashMap key I would go with: `"user.name"` looks and reads easier

**Comment by shssoichiro** [comment]
Added and published in 0.5.0

**Comment by ernestas-poskus** [comment]
Wow you are fast ! :+1:
